=encoding utf8

=head1 NAME

Uzu - Simple static site generator with built-in web server and file-modification change detector.

=head1 USAGE

  uzu webserver <build_dir> 
  uzu init 
  uzu build <layout> 
  uzu serve <layout> 
  uzu push <target>

=head1 DESCRIPTION

Simple static site generator with built-in web server and file-modification change detector.


=head1 INSTALLATION

Install `Perl 6` using the following process:

1. Install `rakudobrew`

    ```bash
    git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    export PATH=~/.rakudobrew/bin:$PATH
    rakudobrew init # Instructions for permanent installation.
    ```

2. Run `rakudobrew init` and follow instructions / output

    It should be something similar to this, changing the username `sam` to your own username:

    ```bash
    echo 'eval "$(/home/sam/.rakudobrew/bin/rakudobrew init -)"' >> ~/.profile
    ```

3. Install latest `Perl 6` and `panda`. 

    Note: This will take about ~5-10 minutes to compile

    ```bash
    rakudobrew build moar 2016.06
    rakudobrew build panda
    ```

4. Install Bailador

    ```
    cd src/
    git clone https://github.com/ufobat/Bailador.git
    cd Bailador/
    panda --notests install .
    ```

6. Clone the repository locally 

    ```
    git clone https://gitlab.com/samcns/uzu.git
    ```

6. Install project requirements

    ```
    cd uzu/
    panda -force install .
    ```
=head1 TODO

* Add tests
* Add build steps to build.pl6
* Uglify JS / CSS
* Build deploy process push to S3

=head1 REPOSITORY

Fork this module on GitLab:
L<https://gitlab.com/samcns/uzu.git>

=head1 BUGS

To report bugs or request features, please use
L<https://gitlab.com/samcns/uzu/issues>

=head1 AUTHOR

Sam Morrison L<https://gitlab.com/u/samcns>

=head1 LICENSE

You can use and distribute this module under the same terms as Perl 6
itself. See the C<LICENSE> file included in this distribution for complete
details.

=cut
